### ISSUE TITLE
Way to setup a bridge?

### ISSUE THREAD

**Issue by iamsaltish** [mattmattandmatt/sky-sr102-router#12]
Hey,

I have flashed the 3766 firmware from _burn_image folder and I seem to have an issue setting up the bridge - almost as it wouldn't change anything at all.

The status does show "Bridge Mode / Unknown", but the SR102's LAN behaves the very same way it's not the bridge. Fake Bridge works partially I guess, as it assigns 10.0.0.2 to the client, but never gets an actual internet connection.

Is there any particular port one would use, or does it simply not work with the VDSL?

I have tried to set up PTM manually on the BCM main page, unlike HG612, I can't seem to assign the interface to the port, rendering it useless.

I realize this is outdated repo and people use HG612 in the best case, however, I believe OEM equipment just gives me a more stable connection with better speeds (45-52mbps @ two diff. hg612 vs almost 60 @ any sky router), so I think it's just better to stay with the sky equipment for now.

Many thanks,
iamsaltish

**Comment by mattmattandmatt** [comment]
My memory from back then is a bit hazy, but I do remember it working.  However I don't think I tried it on a Sky Broadband connection?
If you run it in proper bridge-mode, you will need to make a MER connection used by sky (adding a couple of dhcp options).
So that's why I make the fake bridge.  Unfortunately I can't remember much.

Can you login the router and check the 'ifconfig' interfaces to see if the IP addresses have been assigned.  Particularly the DSL interface to see if it is connecting at all?

**Comment by iamsaltish** [comment]
<img width="629" alt="Screenshot 2021-08-24 at 21 13 03" src="https://user-images.githubusercontent.com/32518770/130683395-4e6d37db-b615-4bc9-86a4-019060df141c.png">
The screenshot above is my current bridge mode.


```bcmsw     Link encap:Ethernet  HWaddr C0:3E:0F:XX:XX:XX  
          UP BROADCAST RUNNING MULTICAST  MTU:2048  Metric:1
          RX packets:0 multicast:0 unicast:0 broadcast:0
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 multicast:0 unicast:0 broadcast:0
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:1000
          RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)
          RX multicast bytes:0 (0.0 B) TX multicast bytes:0 (0.0 B)
          Base address:0xda00 

br0       Link encap:Ethernet  HWaddr C0:3E:0F:XX:XX:XX    
          inet addr:192.168.0.1  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:171915 multicast:43 unicast:171841 broadcast:31
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:349044 multicast:0 unicast:349044 broadcast:0
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:0
          RX bytes:9670882 (9.2 MiB) TX bytes:528040160 (503.5 MiB)
          RX multicast bytes:18104 (17.6 KiB) TX multicast bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr C0:3E:0F:XX:XX:XX  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:172171 multicast:43 unicast:172097 broadcast:31
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:363648 multicast:4 unicast:363634 broadcast:10
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:1000
          RX bytes:12786492 (12.1 MiB) TX bytes:532442343 (507.7 MiB)
          RX multicast bytes:0 (0.0 B) TX multicast bytes:0 (0.0 B)
          

eth1      Link encap:Ethernet  HWaddrC0:3E:0F:XX:XX:XX  
          UP BROADCAST MULTICAST  MTU:2048  Metric:1
          RX packets:0 multicast:0 unicast:0 broadcast:0
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 multicast:0 unicast:0 broadcast:0
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:1000
          RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)
          RX multicast bytes:0 (0.0 B) TX multicast bytes:0 (0.0 B)

eth2      Link encap:Ethernet  HWaddrC0:3E:0F:XX:XX:XX   
          UP BROADCAST MULTICAST  MTU:2048  Metric:1
          RX packets:0 multicast:0 unicast:0 broadcast:0
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 multicast:0 unicast:0 broadcast:0
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:1000
          RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)
          RX multicast bytes:0 (0.0 B) TX multicast bytes:0 (0.0 B)
          

eth3      Link encap:Ethernet  HWaddrC0:3E:0F:XX:XX:XX  
          UP BROADCAST MULTICAST  MTU:2048  Metric:1
          RX packets:0 multicast:0 unicast:0 broadcast:0
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 multicast:0 unicast:0 broadcast:0
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:1000
          RX bytes:0 (0.0 B) TX bytes:0 (0.0 B)
          RX multicast bytes:0 (0.0 B) TX multicast bytes:0 (0.0 B)
          

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:39 multicast:0 unicast:39 broadcast:0
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:39 multicast:0 unicast:39 broadcast:0
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:0
          RX bytes:3439 (3.3 KiB) TX bytes:3439 (3.3 KiB)
          RX multicast bytes:0 (0.0 B) TX multicast bytes:0 (0.0 B)

ptm0      Link encap:Ethernet  HWaddr C0:3E:0F:XX:XX:XX    
          UP BROADCAST RUNNING MULTICAST  MTU:1962  Metric:1
          RX packets:332719 multicast:278 unicast:332434 broadcast:7
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:145149 multicast:276 unicast:144873 broadcast:0
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:1000
          RX bytes:493108908 (470.2 MiB) TX bytes:9818867 (9.3 MiB)
          RX multicast bytes:16680 (16.2 KiB) TX multicast bytes:16560 (16.1 KiB)

ptm0.1    Link encap:Ethernet  HWaddr C0:3E:0F:XX:XX:XX  
          inet addr:5.70.x.y  Bcast:5.70.x+2.255  Mask:255.255.252.0
          UP BROADCAST RUNNING ALLMULTI MULTICAST  MTU:1500  Metric:1
          RX packets:334271 multicast:0 unicast:334271 broadcast:0
          RX errors:0 dropped:0 overruns:0 frame:0
          TX packets:145624 multicast:0 unicast:145624 broadcast:0
          TX errors:0 dropped:0 overruns:0 carrier:0 collisions:0
          txqueuelen:0
          RX bytes:489802050 (467.1 MiB) TX bytes:10426619 (9.9 MiB)
          RX multicast bytes:0 (0.0 B) TX multicast bytes:0 (0.0 B)
```

Regardless of the selected bridge mode (none/normal), the IP is assigned by the sky router's DHCP (192.x). The dhcp61 option doesn't make any difference - I am using pfsense. I will try to disable LAN DHCP on the sky the sr102 and see if that changes anything, but I believe the issue is that none of the ports are actually set to act as a bridge. I will try to get the fake bridge working, probably' would get 10.x address assigned again. I will check the ifconfig again by then.

**Comment by mattmattandmatt** [comment]
I don't think I will be any help, but here goes...

OK, the IP is assigned to the interface, I am going to assume that list above is in non-bridge mode.
I'm assuming your using pfsense the software as a VPN.
The way I got bridge to work was to create a VPN to the router, so it would bring the public IP address/raw traffic to my PC.
I maybe wrong here... If you are using sky broadband you will never get a connection in normal bridge mode without using dhcp61/MER...
Regarding the sky router's DHCP (192.x), I think you can ignore that.  Just connect to 192.168.0.1.


EDIT: I see you wrote "bridge ports".  None of them are isolated ports, you need a PPP? connection to the router when in normal bridge mode.  I feel that you don't want this?

**Comment by iamsaltish** [comment]
Sorry for the delayed answer.

I want to use pfsense as the main router for the traffic and SR102 simply as a modem in a bridge mode.
Having said that, I tested few different configurations and found results as below (on Sky network):
- Bridge Mode (the middle function option under Extras page) - this doesn't seem to do anything practical at all. I can see "Bridge Mode / Unknown", yet the Client (pfsense in this case) will get an address from 192.168.0.x pool. If the DHCP server is disabled on SR102, the Client will not get any IP, despite the Client sending dhcp61. Further investigating that in the Broadcom main page, I have noticed no bridge interface under the WAN Service tab. It could be that the bridge was designed for ATM connections, not PTM (VDSL) ones? In the ADSL case scenario, I don't think Interface Grouping would be necessary at all.
- Fake Bridge. This does give 10.0.0.1 to pfsense and 10.0.0.2 seems to be the gateway. As you mention this would probably require VPN(ala PPP) connection. What details would I use there? This is something I haven't investigated further as I had no idea at all.

I did manage to achieve real bridge mode using SR102 on the Sky network by tweaking some settings in the Broadcom page, however, I am not too sure how to force it to be saved upon reboot. The current configuration does use interface grouping, but again I don't believe it is necessary now.

EDIT: Using "Normal bridge" + Changing IPoE to Bridge in Wan Service does work as intended, but changes upon reboot, re-connection.

**Comment by mattmattandmatt** [comment]
Normal Bridge: Ohh that sounds like a bug, especially when it does not save between reboots.
Unfortunately I have not used that router in a while now, and I don't even know where it is?

I found an old picture here which might help.
![Bridge-Modes-Exp](https://user-images.githubusercontent.com/11339678/132140011-f6aa1012-3e5c-41fe-ac41-a57d6ebba60b.png)
Regarding the PPP connection, can you try that in Normal Bridge?


EDIT: by looking at the picture I made, I have adjusted the Bridge Mode to act differentially.  There was probably a reason for this.  I believe it was to connect to a Windows? PC easier.

**Comment by iamsaltish** [comment]
I've left my setup working overnight and noticed this morning the Wan Service changed from Bridge to IPoE on PTM interface again - consequently, pfsense now has 192.168.x IP. Let me try using the PPPoE configuration, however, I doubt it will work at all.

EDIT: Using PPP as a means of connection on pfsense does not work at all. I assume this mod was done only for ADSL and not VDSL configuration (various references to ATM, and not PTM).

This is how I have achieved a "half-reliable barely working bridge".

1) I've noticed pfsense wan IP has 192.168.x range (mine is 172.20.x) - this already causes double nat issues.
<img width="577" alt="Screenshot 2021-09-06 at 11 09 43" src="https://user-images.githubusercontent.com/32518770/132201816-6db81ff4-2851-4786-baca-813a6b51e398.png">

2) I made sure "Normal Bridge" is ticked under Extras on the Sky page, as "None" does not work at all. Then navigated to 192.168.2.1 and entered the Wan Service tab on the Broadcom website. Noticed the IPoE service forced by the modem and deleted that.
<img width="657" alt="Screenshot 2021-09-06 at 11 09 30" src="https://user-images.githubusercontent.com/32518770/132201678-4a959e4c-df6c-48e2-9d48-77c857f55aab.png">

3) Created a new service, this time in Bridge mode and VLAN 101 with Priority 0, which after saving does work in 50-60% of the cases. The internet LED will turn instantly white, but it might turn to flash orange at some point with no disturbance to the service. IPv6 seems to be working too.
<img width="412" alt="Screenshot 2021-09-06 at 11 10 03" src="https://user-images.githubusercontent.com/32518770/132202293-45e7ecd5-dd5d-46c3-a789-19d488802451.png">

Setup seems to be working, but unreliably - it will break subject to one of two conditions:

- Connection is reset; Sky modem then will reset the configuration back to IPoE and then pfsense gets 192.168.2.2 IP address, despite DHCP being disabled on the SR102 and connections from private IPs blocked (weird, because it doesn't seem to be enforced)
- Device is reset; The configuration will fallback to the original one.
It might take few good restarts and luck to get the IP.

I believe those changes on how "Normal Bridge" would be injected need to be changed on the firmware level to match the VDSL PTM challenge. Sky (at least in my case) does not use ADSL anymore.

Unfortunately, I'm unable to produce updated firmware as I don't seem to have too much luck with recompiling the source  - missing .sh scripts (updateconfig.sh) and few other odd MIPS toolchain issues on 32-bit Linux.

EDIT2: Just noticed my line quality dropped from 49000 to 43000. I don't think my local DLM likes this setup 😬

PFSense regained WAN IP after 5-10 minutes of me reapplying the changes.

<img width="461" alt="Screenshot 2021-09-06 at 11 34 46" src="https://user-images.githubusercontent.com/32518770/132204302-1bb6c0fa-05fb-42c3-82f5-c8dcd4a31a5e.png">

The next step for me will be to reinvestigate if the changes might be saved upon restart with "None" Bridge mode, and if the failure to obtain public IP was an issue due to the ARP Caching on the pfsense side.

**Comment by mattmattandmatt** [comment]
Good info.
If you willing to wait (maybe weeks) I can try to compile a clean copy of the firmware + Broadcom web interface.  However I have a feeling Bridge mode might not work at all.
Regarding the toolchain - you need the one from the ER115 not the SR102 one.  They switched over when they enabled IPv6 on the SR102.
