### ISSUE TITLE
Use as Wifi Bridge

### ISSUE THREAD

**Issue by napsterxp** [mattmattandmatt/sky-sr102-router#13]
Very late to the party here and more of a question than an issue, apologies.

Have found an old SR102 lying around in a drawer at home. Will this custom firmware allow me to use the device as a WiFi bridge? i.e. connect to my 5GHz Home Network via WiFi (ipv4 only, not bothered about v6) and then bridge it to the 4x LAN ports for my wired devices?

Many Thanks

**Comment by mattmattandmatt** [comment]
Hello, its only a 2.4ghz device. Its technicality possible to use it as a bridge.  But it wont work with another normal router.  Sorry
