### ISSUE TITLE
Sky source code links broken

### ISSUE THREAD

**Issue by gazsp** [mattmattandmatt/sky-sr102-router#2]
The link 

http://oss.sky.com/SkyHD/SKY-IHR-2-1-s-3761-R-consumer-release.tar.gz

Is broken (as are the other links on the Sky OSS site for the SR102).

I know this isn't anything to do with you, but would you be able to send me a copy of the source code or a link to it? The Sky OSS email address is now broken as well and they're pretty unresponsive in general.

**Comment by samis** [comment]
I should have a copy of the tarball somewhere. Do you have a preferred file hosting service?

**Comment by gazsp** [comment]
@samis You legend! Dropbox (or anything) is fine really.

I've been bugging Sky on Twitter and the forums but nothing useful from them as yet :-(
