### ISSUE TITLE
USB JTAG cable

### ISSUE THREAD

**Issue by zburgermeiszter** [mattmattandmatt/sky-sr102-router#3]
I bricked my router.

Initially managed to install the firmware as advised, but then I burned the `sky-stock-recovery.img` image. Since then I can not connect to the router via serial, and all LEDs are always on on it.

Also tried to make a JTAG adapter from a Raspberry Pi 3, using [this](https://github.com/oxplot/tjtag-pi) software, but it does seem to be unable to communicate to the router. I might have to use brjtag, as it is a Broadcom device...

Could you please suggest an inexpensive USB JTAG adapter that I could use to reflash my router?

I'm looking to buy [this](https://www.aliexpress.com/item/altera-Mini-Usb-Blaster-Cable-For-CPLD-FPGA-NIOS-JTAG-Altera-Programmer/2038559613.html) or [this](https://www.aliexpress.com/item/AVR-JTAG-ICE-USB-Download-Programmer-Emulator-Aluminum-Shell-Over-Current-Protection-Wide-Voltage-Buffer-Chip/32345324024.html) adapter from Aliexpress.
Please advise if any of these would be suitable to unbrick my router.

Thank you

**Comment by mattmattandmatt** [comment]
From my memory, if all the lights are on.  then its in recovery mode.  OR try to put it into recovery mode.  you know, when you hold in the button and apply the power - then access the mini-http.  But I cant remember the IP off the top of my head, its one of the basic ones like 192.168.0.1.

Regarding an adapter.... I personally use a basic parallel port.  But as long a UrJTAG can use it, it should work.

**Comment by zburgermeiszter** [comment]
So theoretically I don't need the JTAG cable?

I have downloaded the [sky recovery tool](https://www.sky.com/help/articles/download-the-sky-router-recovery-tool) which says, it's in recovery when the amber led is blinking. But on mine all white and the amber is always on.

Tried to hold in the button when I apply the power via the header pins, but still all lights are on, no blinking.

I must use some USB solution as I do not have a PC with parallel port.

**Comment by mattmattandmatt** [comment]
"I apply the power via the header pins" - I assume you dont mean the data header pins  :)
If nothing is coming out of the serail port, then it sounds like you need a USB jtag thingy...  UrJTAG says it will work with these:
https://sourceforge.net/p/urjtag/svn/HEAD/tree/trunk/urjtag/doc/UrJTAG.txt

Did you get anything from the Raspberry Pi jtag....  you should have at least got a eJTAG ID ?
EDIT: P.S. brjtag won't work with this chip.

**Comment by zburgermeiszter** [comment]
I mean apply power on `Gnd` and `+3.3v` pins ([from this photo](https://github.com/mattmattandmatt/sky-sr102-router/blob/master/_debrick-ejtag-bcm963168/SR102-Header-Pinout.jpg)) as I would do for serial access.

It could not read anything, but might be I missed something.

Now waiting for the USB Blaster, and will see what can I do with it.

**Comment by mattmattandmatt** [comment]
errr, thats power out (for a usb serial voltage reference).... I don't recommend powering the device from there it might cause problems?.
It will be best to apply the 5v on the [other power header](https://github.com/mattmattandmatt/sky-sr102-router/blob/master/_pictures/PCB-Bottom.jpg) (bottom corner) connected to the PSU.
Good luck with the USB Blaster...

**Comment by zburgermeiszter** [comment]
I also tried the RPi-JTAG method when I used the original PSU on it.
It could not read anything.
It mist be because the Raspi version is built for Linksys. Or is the communication protocol should be standard on that port?
I'll let you know that I managed to achieve woth the USB Blaster once that's arrived.

Thanks for your advices.

**Comment by zburgermeiszter** [comment]
Hi,

Finally I had some time to play with my Altera USB Blaster.

`lsusb` output:
`Bus 002 Device 020: ID 09fb:6001 Altera Blaster`

`/etc/udev/rules.d/40-basic-permissions.rules`:
`SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device",SYSFS{idVendor}=="09fb" , SYSFS{idProduct}=="6001", MODE="0666" GROUP="dialout"`

also added my user to the `dialout` group using:
`sudo usermod -a -G dialout user`

The `linux-jtag` binary in this repository does not support the `cable UsbBlaster` cable.
So I have installed `urjtag` using `apt-get`.

I also copied the necessary files from the repo to the `/usr/share/urjtag` folder.

It can connect to my blaster, but can not do anything useful with it doe to an error:
```
$ sudo jtag
[sudo] password for ...:

UrJTAG 0.10 #2007
Copyright (C) 2002, 2003 ETC s.r.o.
Copyright (C) 2007, 2008, 2009 Kolja Waschk and the respective authors

UrJTAG is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
There is absolutely no warranty for UrJTAG.

warning: UrJTAG may damage your hardware!
Type "quit" to exit, "help" for help.

jtag> cable UsbBlaster
Connected to libftdi driver.
jtag> detect
warning: TDO seems to be stuck at 0
jtag> 
```

Have you seen this error before?
At this stage I'm unsure whether is it the fault of my USB Blaster or the router is completely died.

Thanks.

**Comment by mattmattandmatt** [comment]
oooh dear...
Perhaps you can try to pull up (via a resistor) the TDO line.  To see if it says
"warning: tdo seems to be stuck at 1" ? - at least then you will know the usbBlaster is working (Hopefully)

Another quick test you can try:
jtag> cable UsbBlaster
jtag> frequency 5000    (or slower)
jtag> idcode
[then a lot of 0's and 1's will appear]  you can try to quickly connect/disconnect the TDO pin to see if you can make a pattern in the display.  This should also prove if the UsbBlaster is working.


I've attached the source code I used/adjusted:
[https://github.com/mattmattandmatt/sky-sr102-router/blob/master/_debrick-ejtag-bcm963168/urjtag-0.10-src-adjusted-cygwin32.zip](urjtag-0.10-src-adjusted-cygwin32.zip)
I personally used Cygwin on Windows.  But I hope that you can re-compile it for linux with the UsbBlaster support.
But I suggested getting you current urjtag partly-working before trying to recompile this one.

**Comment by mattmattandmatt** [comment]
oooh dear...
Perhaps you can try to pull up (via a resistor) the TDO line. To see if it says
"warning: tdo seems to be stuck at 1" ? - at least then you will know the usbBlaster is working (Hopefully)

Another quick test you can try:
jtag> cable UsbBlaster
jtag> frequency 5000 (or slower)
jtag> idcode
[then a lot of 0's and 1's will appear] you can try to quickly connect/disconnect the TDO pin to see if you can make a pattern in the display. This should also prove if the UsbBlaster is working.

I've attached the source code I used/adjusted:
https://github.com/mattmattandmatt/sky-sr102-router/blob/master/_debrick-ejtag-bcm963168/urjtag-0.10-src-adjusted-cygwin32.zip
I personally used Cygwin on Windows. But I hope that you can re-compile it for linux with the UsbBlaster support.
But I suggested getting you current urjtag partly-working before trying to recompile this one.

**Comment by zburgermeiszter** [comment]
Thanks for your reponse.
I have got rid of the router. I have invested much time in it...
