### ISSUE TITLE
Can't burn whole image 

### ISSUE THREAD

**Issue by dralism08** [mattmattandmatt/sky-sr102-router#5]
Hi
I am trying to burn whole image but I got this error 
uClibc.so.0 is not found 
I've read about it it seems that the file has been compiled on x86 and I have an x64 
Any idea how to run it cross platforms 
I am using Ubuntu 18 
Thanks

**Comment by mattmattandmatt** [comment]
Hello, sorry you are going to have to supply more detail.  'burn whole image' only runs on a MIPS processor.  It sounds like a symlink might be missing...  there is a file called "/lib/ld-uClibc.so.0" have a look if it compiled with the rest of the files.  And hopefully the log will tell you why.
Can you try in on x86 VM to see if it makes a difference? I think I used Ubuntu 14.04 x86 (a few years ago)
x64 machines might cause problems with 'fakeroot', so you might want to check the log for that too.
