### ISSUE TITLE
OpenOCD configurations?

### ISSUE THREAD

**Issue by Suphax** [mattmattandmatt/sky-sr102-router#6]
Just wondering if in future you could add OpenOCD configurations. A lot to ask I know but I'm brand new to all this. Thanks in advance no matter the reply :)

**Comment by mattmattandmatt** [comment]
Thats a bit funny,  I used OpenCD on the more recent Sky ER115.

**Comment by mattmattandmatt** [comment]
Thats a bit funny, I used OpenCD on the more recent Sky router.
https://github.com/mattmattandmatt/sky-sr102-router/blob/master/_burn-image/openocd.cfg
This very basic config I used with my parallel port.

Here is something I used with the Sky ER115 (same cpu) - so I could enable the serial port:
-----------------------------------------------------------------------
bcm63168e.cpu arp_halt
bcm63168e.cpu mww 0xb0001014 0x60c
bp 0x80457608 1 hw
resume



# get serial access - do quickly to avoid network problems
bcm63168e.cpu arp_halt
rbp 0x80608304
bp 0x80608304 4 hw
resume

# wait for it...

# swap the serial ports around - assuming firmware 2.06.2189.R or 2.06.2234.R
#   if not, then "bcm63168e.cpu mdw 0x8044DC00 0x300" and look for the values to swap
rbp 0x80608304
bcm63168e.cpu mww 0x8044DCE4 0xB00001A0
bcm63168e.cpu mww 0x8044DCfc 0x2A
bcm63168e.cpu mww 0x8044DD6C 0xB00001A0
bcm63168e.cpu mww 0x8044Dd88 0xB0000180
bcm63168e.cpu mww 0x8044DDA0 0xD
bcm63168e.cpu mww 0x8044DE10 0xB0000180
resume

**Comment by jackcarrdev** [comment]
I assume this will work in debricking?
Either way thanks for the OpenOCD config!

**Comment by mattmattandmatt** [comment]
debricking... errrrm in theory yes.
But I have never tried/programmed it
