### ISSUE TITLE
Wifi bridging

### ISSUE THREAD

**Issue by Billieskeggs** [mattmattandmatt/sky-sr102-router#7]
I’m trying to see if it’s possible to bridge the WiFi from my current isp to this router. Is this supported? 

To clarify

Technicolour router from Sse wired to phone line. 

Sr102 upstairs providing wifi link to allow Ethernet connection to raspberry pi and Humax freebies boxx

TIA

**Comment by mattmattandmatt** [comment]
The Broadcom menu (on the adjusted firmware) has an option called "Wireless Bridge",  but I have never used it.  'For all I know' it only works with other routers with the same "Wireless Bridge" mode.

P.S. r u the 1 who asked about 2704n bricking ?

**Comment by Billieskeggs** [comment]
Ps not me. 

And cheers for the reply

I stuck open-wrt on it in the end and got no luck. Only issue is I can’t roll back to stock or your modified firmware now. 

OpenWrt doesn’t assign ip addresses via DHCP or is responsive via manual allocation can only just interact via serial. 

Will keep tinkering or try understand the build presented by sky and see what I can achieve.

**Comment by mattmattandmatt** [comment]
Oh, from my memory the wi-fi does not work with that version of openwrt.
If you bootup the box in recovery mode (hold in the button during power-on).  Then you can upload the stock firmware: https://github.com/mattmattandmatt/sky-sr102-router/blob/master/_burn-image/sky-stock-recovery.img - I think it uses the IP 192.168.0.1

**Comment by vipt26** [comment]
Hi, I'm trying to connect the sr102 as a wireless bridge to the virgin superhhub 3.  I can then connect my of to sr102 via ethernet as the of doesn't have WiFi. Is this possible with stock firmware? Is it possible with this firmware?
Thanks

**Comment by vipt26** [comment]
Sorry auto correct kicked in.... I can connect desktop PC to sr102 which hopefully can bridge wireless to virgin superhhub 3 which is connected to wan.

**Comment by mattmattandmatt** [comment]
hmm, no idea...  With the stock FW = definitely not.  With the modified FW = 5% chance of working, because virgin media want to to buy there stuff.  Also this old modified FW only uses IPv4 only, which might not work with it.

**Comment by vipt26** [comment]
Ok thanks. I have a virgin superhub connected to wan.  I can't get a wire to my PC so was hoping to connect the super hub to another router wirelessly located at the PC, so I can Ethernet from this router to PC. Since I had the sr102 sitting collecting dust thought I'd see if I could use it.
Any idea whether BT home hub can be used in this was near the PC? Or any other cheap router can do this?
Thanks

**Comment by mattmattandmatt** [comment]
sorry mate, I got no idea about the super hub stuff.   ;(

**Comment by vipt26** [comment]
No worries, might just end up getting an extended or WiFi card instead.
Thanks

**Comment by mattmattandmatt** [comment]
no probs
