### ISSUE TITLE
TDO seems to be stuck at 1

### ISSUE THREAD

**Issue by Saracenz** [mattmattandmatt/sky-sr102-router#9]
Not sure what I'm doing wrong, but I can't get past the 'detect' command. I keep getting 'Warning TDO seems to be stuck at 1'.

I have connected the pins as per the explanation but still keep getting that warning.

Any ideas what may be happening? FYI my router is bricked big time, the power light comes on but everything else is dead (can't connect to any of the ethernet ports and no output from the serial pins on the board.

Thanks

**Comment by mattmattandmatt** [comment]
Hmmm, well you could see if your interface is working correctly...  Connect the TDO to Ground via a resistor (not connected to the router).  And the program should say "Warning TDO seems to be stuck at 0".
Also repeatedly connect & disconnect it from ground while you are scanning.  Just to see if the warning does not appear.

If that works, can you provide more information about how you have connected it please.

**Comment by Saracenz** [comment]
Sorry for the slow reply and thanks for getting back to me.

I have a feeling there is an issue with the parallel port I was using which could explain the error I was getting. Is it possible to use a non parallel port? I have a FT2232 JTAG usb adaptor. Is there any way I can modify the source to use this?

Thanks

**Comment by mattmattandmatt** [comment]
Hmmm, I might? do for a similar router.  I'll gave to find it.

**Comment by Saracenz** [comment]
Ok cool. Is the parallel command in your software fixed or can you specify other devices?

**Comment by mattmattandmatt** [comment]
The parallel port interface works ok for me... I recompiled this one to include the FTD2XXUSB drivers.
```
UsbBlaster    Altera USB-Blaster Cable
FT2232        Generic FTDI FT2232 Cable
```
I remember trying the UsbBlaster, but I did not try the FT2232.  But as they use the same driver? it should work.
https://drive.google.com/file/d/1aRvniaGhiTnM2xvpaBsWYzU4E25U2RWT/view
EDIT: use the jtag.exe in the src directory.

**Comment by Saracenz** [comment]
Great, thank you! I will try that later on and let you know. I assume I issue the same commands as before?

Thanks

**Comment by mattmattandmatt** [comment]
Cheers,
Its the same program, so the "poop" command I added is still the same.  All the other commands are part of the normal urjtag program.
I'm very curious if all works well for you.

**Comment by Saracenz** [comment]
Thanks again for getting back to me.

Ok so unfortunately I'm still having no joy. I am using one of these: 

https://www.ebay.co.uk/itm/FT2232D-JTAG-USB-RV-Debugger-For-Lichee-Tang-RISC-V-Development-Board-C5R8/392243289563?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649

I have that connected to the JTAG pins as per the wiring diagram but when using your jtag.exe I still get TDO seems to be stuck at 1.

Using openocd I've managed to have some very basic success probing the sky br102 over JTAG (although mostly IDCODE related warnings but it does seem to be pulling something back).

**Comment by mattmattandmatt** [comment]
ah, good old "openocd".  I can use to manipulate the memory, but I never wrote a script to erase/write the flash.  This particular Broadcom chip has a weird way of getting the IDCODE.  That's part of the change I had to made to urJtag.

About the pin-out connection:
https://github.com/mattmattandmatt/sky-sr102-router/blob/master/_debrick-ejtag-bcm963168/readme.txt
Did you tie the nTRST to +V (or try Ground).  On the picture I incorrectly called it a I/O reset pulse.
Also are you using any resistors + are you able to take a picture for me to have a look?

**Comment by mattmattandmatt** [comment]
Also going back to an old question.  What happens if you connect the usb adaptor's TDO pin to Ground.  Does it say "TDO seems to be stuck at 0" instead of 1.

**Comment by Saracenz** [comment]
Ahhh I see. I will try the parallel port method again, if i'm honest I don't think I connected nTRST to anything before, which could be the problem! Also, do you know if an old parallel port on a laptop is suitable and the correct voltage?

As for the other question, I connected the USB adaptors TDO pin to the ground on the router but I still got the same error "TDO seems to be stuck at 1"

Thanks for your help. I'm very new to JTAG and debugging microprocessors so all of this is very new to me but very interesting!

**Comment by mattmattandmatt** [comment]
Regarding the parallel port voltage, normally the older it is - the more lightly it is to be 5V.  I think I'm lucky having a 3.3V parallel port on my PC,  However if you connect resistors using either voltage it 'should' work.  
Do you have a multimeter?
If the USB adapter still says "stuck at 1".  I'm guessing it might be a configuration problem.  I'll have to think/guess about this one.

**Comment by mattmattandmatt** [comment]
I'm not sure what type of adapter you have there?.  ebay stuff is not very specific (I don't know the brand LicheeTang). My only suggestion is to use the "help cable" and try all the cables with USB in their name.
`jtag> help cable
Usage: cable DRIVER [DRIVER_OPTS]
Select JTAG cable type.

DRIVER      name of cable
DRIVER_OPTS options for the selected cable

Type "cable DRIVER help" for info about options for cable DRIVER.

List of supported cables:
ARCOM         Arcom JTAG Cable
ByteBlaster   Altera ByteBlaster/ByteBlaster II/ByteBlasterMV Parallel Port Download Cable
UsbBlaster    Altera USB-Blaster Cable
FT2232        Generic FTDI FT2232 Cable
JTAGkey       Amontec JTAGkey (FT2232) Cable
ARM-USB-OCD   Olimex ARM-USB-OCD[-TINY] (FT2232) Cable
gnICE         Analog Devices Blackfin gnICE (FT2232) Cable (EXPERIMENTAL)
OOCDLink-s    OOCDLink-s (FT2232) Cable (EXPERIMENTAL)
Signalyzer    Xverve DT-USB-ST Signalyzer Tool (FT2232) Cable (EXPERIMENTAL)
Turtelizer2   Turtelizer 2 Rev. B (FT2232) Cable (EXPERIMENTAL)
USB-to-JTAG-IF USB to JTAG Interface (FT2232) Cable (EXPERIMENTAL)
Flyswatter    TinCanTools Flyswatter (FT2232) Cable
usbScarab2    KrisTech usbScarabeus2 (FT2232) Cable
DLC5          Xilinx DLC5 JTAG Parallel Cable III
EA253         ETC EA253 JTAG Cable
EI012         ETC EI012 JTAG Cable
IGLOO         Excelpoint IGLOO JTAG Cable
KeithKoep     Keith & Koep JTAG cable
Lattice       Lattice Parallel Port JTAG Cable
MPCBDM        Mpcbdm JTAG cable
TRITON        Ka-Ro TRITON Starterkit II (PXA255/250) JTAG Cable
WIGGLER       Macraigor Wiggler JTAG Cable
WIGGLER2      Modified (with CPU Reset) WIGGLER JTAG Cable
xpc_int       Xilinx Platform Cable USB internal chain
xpc_ext       Xilinx Platform Cable USB external chain
jlink         Segger/IAR J-Link, Atmel SAM-ICE and others.`

**Comment by mattmattandmatt** [comment]
I'm not sure what type of adapter you have there?. ebay stuff is not very specific (I don't know the brand LicheeTang). My only suggestion is to use the "help cable" and try all the cables with USB in their name.
```
jtag> help cable
Usage: cable DRIVER [DRIVER_OPTS]
Select JTAG cable type.

DRIVER name of cable
DRIVER_OPTS options for the selected cable

Type "cable DRIVER help" for info about options for cable DRIVER.

List of supported cables:
ARCOM Arcom JTAG Cable
ByteBlaster Altera ByteBlaster/ByteBlaster II/ByteBlasterMV Parallel Port Download Cable
UsbBlaster Altera USB-Blaster Cable
FT2232 Generic FTDI FT2232 Cable
JTAGkey Amontec JTAGkey (FT2232) Cable
ARM-USB-OCD Olimex ARM-USB-OCD[-TINY] (FT2232) Cable
gnICE Analog Devices Blackfin gnICE (FT2232) Cable (EXPERIMENTAL)
OOCDLink-s OOCDLink-s (FT2232) Cable (EXPERIMENTAL)
Signalyzer Xverve DT-USB-ST Signalyzer Tool (FT2232) Cable (EXPERIMENTAL)
Turtelizer2 Turtelizer 2 Rev. B (FT2232) Cable (EXPERIMENTAL)
USB-to-JTAG-IF USB to JTAG Interface (FT2232) Cable (EXPERIMENTAL)
Flyswatter TinCanTools Flyswatter (FT2232) Cable
usbScarab2 KrisTech usbScarabeus2 (FT2232) Cable
DLC5 Xilinx DLC5 JTAG Parallel Cable III
EA253 ETC EA253 JTAG Cable
EI012 ETC EI012 JTAG Cable
IGLOO Excelpoint IGLOO JTAG Cable
KeithKoep Keith & Koep JTAG cable
Lattice Lattice Parallel Port JTAG Cable
MPCBDM Mpcbdm JTAG cable
TRITON Ka-Ro TRITON Starterkit II (PXA255/250) JTAG Cable
WIGGLER Macraigor Wiggler JTAG Cable
WIGGLER2 Modified (with CPU Reset) WIGGLER JTAG Cable
xpc_int Xilinx Platform Cable USB internal chain
xpc_ext Xilinx Platform Cable USB external chain
jlink Segger/IAR J-Link, Atmel SAM-ICE and others.
```

**Comment by mattmattandmatt** [comment]
I'm not sure what type of adapter you have there?. ebay stuff is not very specific (I don't know the brand LicheeTang). My only suggestion is to use the "help cable" and try all the cables with USB\FT2232 in their name.

```
jtag> help cable
Usage: cable DRIVER [DRIVER_OPTS]
Select JTAG cable type.

DRIVER name of cable
DRIVER_OPTS options for the selected cable

Type "cable DRIVER help" for info about options for cable DRIVER.

List of supported cables:
ARCOM Arcom JTAG Cable
ByteBlaster Altera ByteBlaster/ByteBlaster II/ByteBlasterMV Parallel Port Download Cable
UsbBlaster Altera USB-Blaster Cable
FT2232 Generic FTDI FT2232 Cable
JTAGkey Amontec JTAGkey (FT2232) Cable
ARM-USB-OCD Olimex ARM-USB-OCD[-TINY] (FT2232) Cable
gnICE Analog Devices Blackfin gnICE (FT2232) Cable (EXPERIMENTAL)
OOCDLink-s OOCDLink-s (FT2232) Cable (EXPERIMENTAL)
Signalyzer Xverve DT-USB-ST Signalyzer Tool (FT2232) Cable (EXPERIMENTAL)
Turtelizer2 Turtelizer 2 Rev. B (FT2232) Cable (EXPERIMENTAL)
USB-to-JTAG-IF USB to JTAG Interface (FT2232) Cable (EXPERIMENTAL)
Flyswatter TinCanTools Flyswatter (FT2232) Cable
usbScarab2 KrisTech usbScarabeus2 (FT2232) Cable
DLC5 Xilinx DLC5 JTAG Parallel Cable III
EA253 ETC EA253 JTAG Cable
EI012 ETC EI012 JTAG Cable
IGLOO Excelpoint IGLOO JTAG Cable
KeithKoep Keith & Koep JTAG cable
Lattice Lattice Parallel Port JTAG Cable
MPCBDM Mpcbdm JTAG cable
TRITON Ka-Ro TRITON Starterkit II (PXA255/250) JTAG Cable
WIGGLER Macraigor Wiggler JTAG Cable
WIGGLER2 Modified (with CPU Reset) WIGGLER JTAG Cable
xpc_int Xilinx Platform Cable USB internal chain
xpc_ext Xilinx Platform Cable USB external chain
jlink Segger/IAR J-Link, Atmel SAM-ICE and others.
```

**Comment by Saracenz** [comment]
Ok, I do have a multimeter so I will measure the voltage and find out. I have a couple other spare laptops which are old and have parallel ports so ill try those also.

Ahh I did not realise about that command, I will try all of those USB\FT2232 types, the dongle is labelled as  'Sipeed USB-JTAG/TTL' but i'm not sure whats actually under the hood.

Incidentally, when I run the 'help cable' command I get a different list to what you get? I am using tjhe jtag.exe from the src folder in the .7z archive you uploaded. The version output shows:

UrJTAG 0.10 #1504
Copyright (C) 2002, 2003 ETC s.r.o.
Copyright (C) 2007, 2008, 2009 Kolja Waschk and the respective authors

**Comment by mattmattandmatt** [comment]
oooops, I uploaded the wrong one... second try lucky:
https://drive.google.com/open?id=1qOXGeqb-inpxDwSlQ0FMpvyxKJtZIKNl
I not very good at version revision, so I mixed stuff up.   :o

Also, I noticed I changed the command from 'poop' to 'poop2'.  I don't know why I did that?.  I hope it still works with the SR102, because I adjusted this program to work with the 'ER115'.
